### ISSUE TITLE
length not defined in server.js:63:65

### ISSUE THREAD

**Issue by aravindiiitb** [dheerosaur/nyc-holiday-taxi-viz#1]
var halfKey = Math.floor(rawData.length / 2);
                                                         ^
TypeError: Cannot read property 'length' of undefined

not able to resolve it. Can you please help me

Thanks,
Aravind

**Comment by dheerosaur** [comment]
The project needs a database to run. Please check line 8 in server.js.
Attaching a sample DB with just the first day's data now and closing.

[db.gz](https://github.com/dheerosaur/nyc-holiday-taxi-viz/files/1058834/db.gz)
